### ISSUE TITLE
Installing source build via pip and running start_pairinteractin_gui fails with: ImportError: libpicomplex.so

### ISSUE THREAD

**Issue by Patschke** [pairinteraction/pairinteraction#173]
After building pairinteraction from the latest release and installation via pip, starting pairinteraction failed with following error:

```console
[~]$ start_pairinteraction_gui         
Import Modules ...     0 %
/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Import Modules ...    20 %
Import Modules ...    40 %
Traceback (most recent call last):
  File "/usr/bin/start_pairinteraction_gui", line 23, in <module>
    runpy.run_module("pairinteraction_gui.pairinteraction_app.app", {}, "__main__")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pairinteraction_app/app.py", line 151, in <module>
    from pairinteraction_gui.pairinteraction_app.pipy_thread import PipyThread
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pairinteraction_app/pipy_thread.py", line 14, in <module>
    from pairinteraction_gui import pipy
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pipy/__init__.py", line 13, in <module>
    from pairinteraction_gui.pipy.atom import Atom, AtomOne, AtomTwo, atom_from_config
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pipy/atom.py", line 11, in <module>
    from pairinteraction import picomplex
  File "/usr/lib/python3.11/site-packages/pairinteraction/picomplex.py", line 12, in <module>
    from . import _picomplex
ImportError: libpicomplex.so: cannot open shared object file: No such file or directory
```

In the actual build directory, the `libpicomplex.so` file was created (in the `build/pairinteraction` directory), but pip did not copy it over to `usr/lib/python3.11/site-packages/pairinteraction`, thus python would not find it. After adding it there, pairinteraction launches again. 

I installed using the following PKGBUILD (and frankly I am fairly certain, that it worked fine in the past...): 
<details>
  <summary>PKGBUILD</summary>
    
  ```PKGBUILD
# Contributor: Patrick Mischke

pkgname='python-pairinteraction'
_name='pairinteraction'
_py="py3"
pkgver=0.9.9
pkgrel=2
pkgdesc="A Rydberg Interaction Calculator"
url="https://github.com/pairinteraction/pairinteraction"
depends=('python-numpy' 'python-scipy' 'python-pint' 'python-pyqtgraph' 'python-pyzmq' 'sqlite' 'gsl' 'swig' 'lapacke')
makedepends=('python-pip' 'doctest' 'fmt' 'eigen' 'boost')
license=('GPL3' 'LGPL3')
arch=('x86_64')
options=('!buildflags' 'staticlibs' '!strip' 'libtool')
source=("https://github.com/pairinteraction/pairinteraction/archive/refs/tags/v$pkgver.tar.gz")

sha256sums=("800529dac49a7723969f4d0388ee66869c8728178b6b17d13f12856204b79fc2")

build() {
  cd $srcdir/pairinteraction-$pkgver
  mkdir build
  cd build
  cmake ..
  make -j 8
}

package() {
  cd "$srcdir/pairinteraction-$pkgver/build"
  PIP_CONFIG_FILE=/dev/null pip install --isolated --root="$pkgdir" --ignore-installed --no-deps .
}

  ```
</details>

Adding a line (`cp pairinteraction/libpicomplex.so "$pkgdir/usr/lib/python3.11/site-packages/pairinteraction/libpicomplex.so"`) to the `package()` section to copy over the `libpicomplex.so` after `pip` has done its job resolved the issue. I still wonder why I have to do that...

Some (maybe?) relevant information on my system: 
```console
[~]$ pip --version            
pip 23.2.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
[~]$ python --version                                
Python 3.11.5
[~]$ uname -r                                                       
6.5.7-arch1-1
```

Everything runs fine for me now, but it seemed like something does not work quite the way it's supposed to, so I decided to file an issue anyway.

**Comment by hmenke** [comment]
Sorry for the long wait. This should have been fixed as part of https://github.com/pairinteraction/pairinteraction/commit/b353abc5342251adb658ab9f35a8968aa571357e. Can you please try again?

**Comment by Patschke** [comment]
Looks like it works fine now, thanks. The build size has also been reduced from 130 MiB to 26 MiB, so perhaps the installation in overall cleaner? 

Given that I was able to run pairinteraction just fine, the long wait was no issue at all. Thanks again for fixing (and maintaining this entire project)!
